export default {
  login: 'Ayush4web',
  id: 85270991,
  node_id: 'MDQ6VXNlcjg1MjcwOTkx',
  avatar_url: 'https://avatars.githubusercontent.com/u/85270991?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Ayush4web',
  html_url: 'https://github.com/Ayush4web',
  followers_url: 'https://api.github.com/users/Ayush4web/followers',
  following_url:
    'https://api.github.com/users/Ayush4web/following{/other_user}',
  gists_url: 'https://api.github.com/users/Ayush4web/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Ayush4web/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Ayush4web/subscriptions',
  organizations_url: 'https://api.github.com/users/Ayush4web/orgs',
  repos_url: 'https://api.github.com/users/Ayush4web/repos',
  events_url: 'https://api.github.com/users/Ayush4web/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Ayush4web/received_events',
  type: 'User',
  site_admin: false,
  name: 'Ayush Choubey',
  company: 'me',
  blog: 'https://ayushchoubey.netlify.app',
  location: 'Bhopal, India',
  email: null,
  hireable: null,
  bio: 'Developing The New World.',
  twitter_username: null,
  public_repos: 24,
  public_gists: 0,
  followers: 0,
  following: 3,
  created_at: '2021-06-03T04:00:47Z',
  updated_at: '2022-02-17T17:47:46Z',
}